- name: Lancer le GitLab Runner (Docker)
  community.docker.docker_container:
    name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    state: started
    restart_policy: always
    etc_hosts:
      "gitlab.grp-ay.lab": "10.212.213.20"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /usr/local/share/ca-certificates/grp-ay-ca.crt:/etc/gitlab-runner/rootCA.crt:ro